/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlin_sample

class CrsTransformation {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println(CrsTransformation().greeting)
}
