/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package groovy_sample

import spock.lang.Specification

class CrsTransformationTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new CrsTransformation()

        when:
        def result = app.greeting

        then:
        result != null
    }
}
