/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_sample;

public class CrsTransformation
{
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new CrsTransformation().getGreeting());
    }
}
