/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlin_sample

import kotlin.test.Test
import kotlin.test.assertNotNull

class CrsTransformationTest {

    // TODO maybe add some test here ...
    // But if you want to see tests then there are many Java tests of the Kotlin code 
    // in the module "crs-transformation-adapter-test" 



//    @Test fun testAppHasAGreeting() {
//        val classUnderTest = CrsTransformation()
//        assertNotNull(classUnderTest.greeting, "app should have a greeting")
//    }
}
