/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package groovy_sample

class CrsTransformation {
    String getGreeting() {
        return 'Hello world.'
    }

    static void main(String[] args) {
        println new CrsTransformation().greeting
    }
}
