/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_sample;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class CrsTransformationTest
{
    @Test public void appHasAGreeting() {
        CrsTransformation classUnderTest = new CrsTransformation();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
